export type PhoneBrand = "Apple" | "Samsung";
export type PhoneSpecificationKey = "display" | "camera" | "weight" | "battery" | "connectivity";
export type PhoneMedia = { id:string; src:string; width:number; height:number; alt:string; source:"project"|"manufacturer"|"SAmobile"; sourceUrl:string|null; usageStatus:"approved"|"reference-only"|"placeholder"; dateChecked:string };
export type PhoneStorageVariant = { id:string; capacityGb:number; priceKrw:number|null };
export type PhoneColor = { id:string; name:string; swatch?:string; imageId?:string; availability:"standard"|"manufacturer-exclusive" };
export type PhoneSpecification = { key:PhoneSpecificationKey; value:string };
export type Phone = { id:string; slug:string; brand:PhoneBrand; model:string; media:readonly PhoneMedia[]; storageVariants:readonly PhoneStorageVariant[]; colors:readonly PhoneColor[]; specifications:readonly PhoneSpecification[]; status:"manufacturer-current"|"manufacturer-relevant"; commercialVerificationStatus:"price-unverified"|"price-verified"; source:{manufacturer:PhoneBrand;url:string;dateChecked:string;verifiedFields:readonly string[]} };
export type FinancingConfiguration = { annualRateBasisPoints:number; termsMonths:readonly number[] };
export const phoneFinancing:FinancingConfiguration={annualRateBasisPoints:600,termsMonths:[6,12]};

const dateChecked="2026-09-22";
const appleMedia=(slug:string,model:string,colors:PhoneColor[],sourceUrl:string):PhoneMedia[]=>colors.filter(item=>item.availability==="standard").map(item=>({id:item.id,src:`/products/apple/${slug}/${item.id.replaceAll("-","")}.png`,width:940,height:1112,alt:`${model} in ${item.name}`,source:"manufacturer",sourceUrl,usageStatus:"reference-only",dateChecked}));
const samsungMedia=(slug:string,model:string,colors:PhoneColor[],sourceUrl:string):PhoneMedia[]=>colors.filter(item=>item.availability==="standard").map(item=>({id:item.id,src:`/products/samsung/${slug}/${item.id}.jpg`,width:1600,height:864,alt:`${model} in ${item.name}`,source:"manufacturer",sourceUrl,usageStatus:"reference-only",dateChecked}));
const storage=(id:string,values:number[]):PhoneStorageVariant[]=>values.map(capacityGb=>({id:`${id}-${capacityGb}`,capacityGb,priceKrw:null}));
const color=(id:string,name:string,swatch:string,availability:PhoneColor["availability"]="standard"):PhoneColor=>({id,name,swatch,imageId:availability==="standard"?id:undefined,availability});
const source=(manufacturer:PhoneBrand,url:string,verifiedFields:string[])=>({manufacturer,url,dateChecked,verifiedFields});
const appleColors={pro:[color("black","Black","#242424"),color("silver","Silver","#d9d9d6"),color("glacier","Glacier","#cadbe1"),color("burgundy","Burgundy","#713541")],regular:[color("black","Black","#242424"),color("white","White","#f4f3ef"),color("mist-blue","Mist Blue","#b9cede"),color("sage","Sage","#a8b6a3"),color("lavender","Lavender","#c5b8d4")]};
const samsungColors=[color("cobalt-violet","Cobalt Violet","#6c6185"),color("sky-blue","Sky Blue","#b7d2e4"),color("black","Black","#242424"),color("white","White","#f2f2ef"),color("pink-gold","Pink Gold","#ddbbb0","manufacturer-exclusive"),color("silver-shadow","Silver Shadow","#a6a7a9","manufacturer-exclusive")];
const apple=(id:string,model:string,capacities:number[],colors:PhoneColor[],specifications:PhoneSpecification[],url:string):Phone=>({id,slug:id,brand:"Apple",model,media:appleMedia(id,model,colors,url),storageVariants:storage(id,capacities),colors,specifications,status:"manufacturer-current",commercialVerificationStatus:"price-unverified",source:source("Apple",url,["model","storage","colors","display","camera","weight","battery"])});
const samsung=(id:string,model:string,capacities:number[],colors:PhoneColor[],specifications:PhoneSpecification[],url:string,foldable=false):Phone=>({id,slug:id,brand:"Samsung",model,media:samsungMedia(id,model,colors,url),storageVariants:storage(id,capacities),colors,specifications,status:foldable?"manufacturer-relevant":"manufacturer-current",commercialVerificationStatus:"price-unverified",source:source("Samsung",url,["model","storage","colors","exclusive colors","display","camera","weight","battery"])});
const specs=(display:string,camera:string,weight:string,battery:string,connectivity="5G · Wi‑Fi · SIM/eSIM"):PhoneSpecification[]=>[{key:"display",value:display},{key:"camera",value:camera},{key:"weight",value:weight},{key:"battery",value:battery},{key:"connectivity",value:connectivity}];

export const phones:readonly Phone[]=[
  apple("iphone-18-pro","iPhone 18 Pro",[256,512,1024,2048],appleColors.pro,specs("15.9cm Super Retina XDR OLED","48MP Pro Fusion camera system","211g","Up to 34 hours video playback"),"https://www.apple.com/kr/iphone-18-pro/specs/"),
  apple("iphone-18-pro-max","iPhone 18 Pro Max",[256,512,1024,2048],appleColors.pro,specs("17.4cm Super Retina XDR OLED","48MP Pro Fusion camera system","249g","Up to 43 hours video playback"),"https://www.apple.com/kr/iphone-18-pro/specs/"),
  apple("iphone-17","iPhone 17",[256,512],appleColors.regular,specs("15.9cm Super Retina XDR OLED · up to 120Hz","48MP Dual Fusion camera system","177g","All-day battery"),"https://www.apple.com/kr/iphone-17/specs/"),
  apple("iphone-air","iPhone Air",[256,512,1024],[color("sky-blue","Sky Blue","#bdd1df"),color("light-gold","Light Gold","#ded2b0"),color("cloud-white","Cloud White","#efefeb"),color("space-black","Space Black","#27282a")],specs("16.6cm Super Retina XDR OLED","48MP Fusion camera system","165g","Up to 27 hours video playback","5G · Wi‑Fi · dual eSIM"),"https://www.apple.com/kr/iphone-air/specs/"),
  apple("iphone-17e","iPhone 17e",[256,512],[color("black","Black","#242424"),color("white","White","#f4f3ef"),color("soft-pink","Soft Pink","#e9ced1")],specs("15.4cm Super Retina XDR OLED","48MP 2-in-1 camera system","170g","Manufacturer-rated battery performance"),"https://www.apple.com/kr/iphone-17e/specs/"),
  samsung("galaxy-s26","Galaxy S26",[256,512],samsungColors,specs("159.3mm FHD+ Dynamic AMOLED 2X · 120Hz","50MP + 10MP + 12MP rear cameras","167g","4,300mAh typical"),"https://www.samsung.com/sec/smartphones/galaxy-s26/specs/"),
  samsung("galaxy-s26-plus","Galaxy S26+",[256,512],samsungColors,specs("169.1mm QHD+ Dynamic AMOLED 2X · 120Hz","50MP + 10MP + 12MP rear cameras","190g","4,900mAh typical"),"https://www.samsung.com/sec/smartphones/galaxy-s26/specs/"),
  samsung("galaxy-s26-ultra","Galaxy S26 Ultra",[256,512,1024],samsungColors.slice(0,4),specs("174.9mm QHD+ Dynamic AMOLED 2X · 120Hz","200MP main · 50MP ultra-wide · telephoto","214g","5,000mAh typical"),"https://www.samsung.com/sec/smartphones/galaxy-s26-ultra/"),
  samsung("galaxy-z-flip8","Galaxy Z Flip8",[256,512],[color("pink","Pink","#e6bcc8"),color("graphite","Graphite","#494b4f"),color("cream","Cream","#e8e0ca"),color("mint","Mint","#b7d7c9","manufacturer-exclusive")],specs("174.1mm main · 104.8mm cover display","50MP + 12MP rear cameras","180g","4,300mAh typical"),"https://org-sec-b2c.samsung.com/sec/smartphones/galaxy-z-flip8/specs/",true),
  samsung("galaxy-z-fold8","Galaxy Z Fold8",[256,512,1024],[color("lavender","Lavender","#b7a8c9"),color("graphite","Graphite","#494b4f"),color("cream","Cream","#e8e0ca"),color("pistachio","Pistachio","#b8c9a9","manufacturer-exclusive")],specs("Large foldable main display · cover display","50MP dual rear camera system","201g","Manufacturer-rated battery"),"https://org-sec-b2c.samsung.com/sec/smartphones/galaxy-z-fold8/",true),
];
export const selectableColors=(phone:Phone)=>phone.colors.filter(item=>item.availability==="standard");
export const resolvePhoneMedia=(phone:Phone,colorId:string)=>{const selected=selectableColors(phone).find(item=>item.id===colorId);return phone.media.find(item=>item.id===selected?.imageId)??phone.media[0]};
export const hasVerifiedPrice=(phone:Phone)=>phone.commercialVerificationStatus!=="price-unverified"&&phone.storageVariants.every(item=>item.priceKrw!==null);
export const filterPhones=(phones:readonly Phone[],brand:"all"|PhoneBrand)=>brand==="all"?phones:phones.filter(phone=>phone.brand===brand);
